// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIUdj5T-it5HMIsiMKqQ4vwnzXcr0RW8',
    appId: '1:215153960663:web:bce9b8f643543f6939f292',
    messagingSenderId: '215153960663',
    projectId: 'anzaconnect',
    authDomain: 'anzaconnect.firebaseapp.com',
    storageBucket: 'anzaconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhad0b3BgwurWxMOb1GA8dCTA3FySqIeU',
    appId: '1:215153960663:android:5b400ab8bc5ef68d39f292',
    messagingSenderId: '215153960663',
    projectId: 'anzaconnect',
    storageBucket: 'anzaconnect.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCve28KRCa-Xajuy4z74QT9DMkZhp4YWj8',
    appId: '1:215153960663:ios:c274c40bbfe0d0b139f292',
    messagingSenderId: '215153960663',
    projectId: 'anzaconnect',
    storageBucket: 'anzaconnect.firebasestorage.app',
    androidClientId: '215153960663-36ibq162vs2aa83rf6atm7qn0os5ocus.apps.googleusercontent.com',
    iosClientId: '215153960663-oap6qdst0ofgg384fq8766vrlildf5i0.apps.googleusercontent.com',
    iosBundleId: 'com.example.connect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCve28KRCa-Xajuy4z74QT9DMkZhp4YWj8',
    appId: '1:215153960663:ios:c274c40bbfe0d0b139f292',
    messagingSenderId: '215153960663',
    projectId: 'anzaconnect',
    storageBucket: 'anzaconnect.firebasestorage.app',
    androidClientId: '215153960663-36ibq162vs2aa83rf6atm7qn0os5ocus.apps.googleusercontent.com',
    iosClientId: '215153960663-oap6qdst0ofgg384fq8766vrlildf5i0.apps.googleusercontent.com',
    iosBundleId: 'com.example.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANIUdj5T-it5HMIsiMKqQ4vwnzXcr0RW8',
    appId: '1:215153960663:web:e69b0eb1ac42845e39f292',
    messagingSenderId: '215153960663',
    projectId: 'anzaconnect',
    authDomain: 'anzaconnect.firebaseapp.com',
    storageBucket: 'anzaconnect.firebasestorage.app',
  );
}
